# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import dw_data_v3_pb2 as dw__data__v3__pb2


class DwdataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUscIdByEnterpriseName = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetUscIdByEnterpriseName',
                request_serializer=dw__data__v3__pb2.GetUscIdByEnterpriseNameReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetUscIdByEnterpriseNameResp.FromString,
                )
        self.GetEnterpriseInfo = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEnterpriseInfo',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataDictResp.FromString,
                )
        self.GetEntEquityTransparency = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEntEquityTransparency',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEntEquityTransparencyConclusion = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEntEquityTransparencyConclusion',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataDictResp.FromString,
                )
        self.GetEntShareholders = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEntShareholders',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEntInvestment = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEntInvestment',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEntFinancing = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEntFinancing',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEntBranches = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEntBranches',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetCaseRegistrationInfo = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetCaseRegistrationInfo',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetForeclosureDisposition = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetForeclosureDisposition',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetExecutive = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetExecutive',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetHistoricalExecutive = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetHistoricalExecutive',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEquityFrozen = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEquityFrozen',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetHighConsumptionRestriction = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetHighConsumptionRestriction',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetCourtAnnouncement = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetCourtAnnouncement',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEnterpriseManagerInfo = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEnterpriseManagerInfo',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetDiscreditedDebtor = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetDiscreditedDebtor',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetJudicialStatics = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetJudicialStatics',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEnterpriseCredential = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEnterpriseCredential',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEnterpriseRankingList = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEnterpriseRankingList',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetEntRankingListResp.FromString,
                )
        self.GetEnterpriseIndustry = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEnterpriseIndustry',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )
        self.GetEnterpriseProduct = channel.unary_unary(
                '/api.dwdata.v3.DwdataService/GetEnterpriseProduct',
                request_serializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
                response_deserializer=dw__data__v3__pb2.GetDataListResp.FromString,
                )


class DwdataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUscIdByEnterpriseName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnterpriseInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntEquityTransparency(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntEquityTransparencyConclusion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntShareholders(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntInvestment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntFinancing(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEntBranches(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCaseRegistrationInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetForeclosureDisposition(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecutive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistoricalExecutive(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEquityFrozen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHighConsumptionRestriction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCourtAnnouncement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnterpriseManagerInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDiscreditedDebtor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJudicialStatics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnterpriseCredential(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnterpriseRankingList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnterpriseIndustry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEnterpriseProduct(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DwdataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUscIdByEnterpriseName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUscIdByEnterpriseName,
                    request_deserializer=dw__data__v3__pb2.GetUscIdByEnterpriseNameReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetUscIdByEnterpriseNameResp.SerializeToString,
            ),
            'GetEnterpriseInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnterpriseInfo,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataDictResp.SerializeToString,
            ),
            'GetEntEquityTransparency': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntEquityTransparency,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEntEquityTransparencyConclusion': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntEquityTransparencyConclusion,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataDictResp.SerializeToString,
            ),
            'GetEntShareholders': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntShareholders,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEntInvestment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntInvestment,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEntFinancing': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntFinancing,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEntBranches': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEntBranches,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetCaseRegistrationInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCaseRegistrationInfo,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetForeclosureDisposition': grpc.unary_unary_rpc_method_handler(
                    servicer.GetForeclosureDisposition,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetExecutive': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecutive,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetHistoricalExecutive': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistoricalExecutive,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEquityFrozen': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEquityFrozen,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetHighConsumptionRestriction': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHighConsumptionRestriction,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetCourtAnnouncement': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCourtAnnouncement,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEnterpriseManagerInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnterpriseManagerInfo,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetDiscreditedDebtor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDiscreditedDebtor,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetJudicialStatics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJudicialStatics,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEnterpriseCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnterpriseCredential,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEnterpriseRankingList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnterpriseRankingList,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetEntRankingListResp.SerializeToString,
            ),
            'GetEnterpriseIndustry': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnterpriseIndustry,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
            'GetEnterpriseProduct': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEnterpriseProduct,
                    request_deserializer=dw__data__v3__pb2.GetDataBeforeTimePointReq.FromString,
                    response_serializer=dw__data__v3__pb2.GetDataListResp.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'api.dwdata.v3.DwdataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DwdataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUscIdByEnterpriseName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetUscIdByEnterpriseName',
            dw__data__v3__pb2.GetUscIdByEnterpriseNameReq.SerializeToString,
            dw__data__v3__pb2.GetUscIdByEnterpriseNameResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnterpriseInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEnterpriseInfo',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataDictResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntEquityTransparency(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEntEquityTransparency',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntEquityTransparencyConclusion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEntEquityTransparencyConclusion',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataDictResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntShareholders(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEntShareholders',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntInvestment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEntInvestment',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntFinancing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEntFinancing',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEntBranches(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEntBranches',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCaseRegistrationInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetCaseRegistrationInfo',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetForeclosureDisposition(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetForeclosureDisposition',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetExecutive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetExecutive',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHistoricalExecutive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetHistoricalExecutive',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEquityFrozen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEquityFrozen',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetHighConsumptionRestriction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetHighConsumptionRestriction',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCourtAnnouncement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetCourtAnnouncement',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnterpriseManagerInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEnterpriseManagerInfo',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDiscreditedDebtor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetDiscreditedDebtor',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJudicialStatics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetJudicialStatics',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnterpriseCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEnterpriseCredential',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnterpriseRankingList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEnterpriseRankingList',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetEntRankingListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnterpriseIndustry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEnterpriseIndustry',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetEnterpriseProduct(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/api.dwdata.v3.DwdataService/GetEnterpriseProduct',
            dw__data__v3__pb2.GetDataBeforeTimePointReq.SerializeToString,
            dw__data__v3__pb2.GetDataListResp.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
