version: '3.1'
services:
  api:
    build:
      context: ./micros-api
      dockerfile: Dockerfile
    ports:
      - "8009:8000"
    depends_on:
      - dwData
      - pipeline
    volumes:
        - ./micros-api/configs:/data/conf

  dwData:
    build:
      context: ./micros-dw
      dockerfile: Dockerfile
    ports:
      - "50052:50052"
    environment:
      - DWDATA_URI=api:50052
    volumes:
      - ./micros-dw/configs:/data/conf

  pipeline:
    build:
      context: ./micros-pipeline
      dockerfile: Dockerfile
    ports:
      - "50053:50053"
    depends_on:
      - dwData
#    volumes:
#      - ./micros-pipeline/configs:/data/conf


