# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0epipeline.proto\x12\x0f\x61pi.pipeline.v1\x1a\x1cgoogle/protobuf/struct.proto\"b\n\x14GetContentProcessReq\x12\x12\n\ncontent_id\x18\x01 \x01(\x03\x12\x36\n\x0ereport_version\x18\x02 \x01(\x0e\x32\x1e.api.pipeline.v1.ReportVersion\"j\n\x15GetContentProcessResp\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0c\n\x04\x63ode\x18\x02 \x01(\x05\x12\x0b\n\x03msg\x18\x03 \x01(\t\x12%\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct*0\n\x0e\x43ontentVersion\x12\x0e\n\nCONTENT_V1\x10\x00\x12\x0e\n\nCONTENT_V2\x10\x01*+\n\rReportVersion\x12\x06\n\x02V2\x10\x00\x12\x06\n\x02V3\x10\x01\x12\n\n\x06LATEST\x10\x02\x32w\n\x0fPipelineService\x12\x64\n\x11GetContentProcess\x12%.api.pipeline.v1.GetContentProcessReq\x1a&.api.pipeline.v1.GetContentProcessResp\"\x00\x42H\n\x0f\x61pi.pipeline.v1B\nPipelineV1P\x01Z\'micros-py/api/py/pipeline/v1;pipelineV1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipeline_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\017api.pipeline.v1B\nPipelineV1P\001Z\'micros-py/api/py/pipeline/v1;pipelineV1'
  _globals['_CONTENTVERSION']._serialized_start=273
  _globals['_CONTENTVERSION']._serialized_end=321
  _globals['_REPORTVERSION']._serialized_start=323
  _globals['_REPORTVERSION']._serialized_end=366
  _globals['_GETCONTENTPROCESSREQ']._serialized_start=65
  _globals['_GETCONTENTPROCESSREQ']._serialized_end=163
  _globals['_GETCONTENTPROCESSRESP']._serialized_start=165
  _globals['_GETCONTENTPROCESSRESP']._serialized_end=271
  _globals['_PIPELINESERVICE']._serialized_start=368
  _globals['_PIPELINESERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
