server:
  http:
    addr: 0.0.0.0:8009
    timeout: 1s
  grpc:
    addr: 0.0.0.0:50052
    timeout: 1s
data:
  database:
    driver: mysql
    #    source: root:adminpassword@tcp(192.168.31.158:3306)/data_warehouse?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
    source: blscf:Dzkw46MZDbB7axDC@tcp(10.0.232.121:3308)/bl_business?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  nats:
    #    uri: "nats://dev:password@192.168.31.158:4222"
    uri: "nats://brillinkdata:MFmi9jAB@10.0.232.121:4222"
    activate: true
  blAuth:
    client_id: "default"
    client_secret: "admin123"
    url: "http://10.0.232.22:9080"
    path_check_token: "/admin-api/system/oauth2/check-token"
    database:
      driver: mysql
      source: root:123@qwe@tcp(10.0.203.71:3306)/ruoyi-vue-pro?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
