// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v3.21.12
// source: api/graph/v1/graph_tree.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationTreeGraphServiceGetChildren = "/api.graph.v1.TreeGraphService/GetChildren"
const OperationTreeGraphServiceGetPathBetween = "/api.graph.v1.TreeGraphService/GetPathBetween"
const OperationTreeGraphServiceGetTitleAutoComplete = "/api.graph.v1.TreeGraphService/GetTitleAutoComplete"
const OperationTreeGraphServiceGetTreeNode = "/api.graph.v1.TreeGraphService/GetTreeNode"

type TreeGraphServiceHTTPServer interface {
	GetChildren(context.Context, *PgIdReq) (*TreeNodesResp, error)
	GetPathBetween(context.Context, *GetPathReq) (*TreeNodeResp, error)
	GetTitleAutoComplete(context.Context, *TitleAutoCompleteReq) (*TitleAutoCompleteResp, error)
	GetTreeNode(context.Context, *IdReq) (*TreeNodeResp, error)
}

func RegisterTreeGraphServiceHTTPServer(s *http.Server, srv TreeGraphServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/micros/graph/v1/tree/node", _TreeGraphService_GetTreeNode0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/tree/children", _TreeGraphService_GetChildren0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/tree/title-autocomplete", _TreeGraphService_GetTitleAutoComplete0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/tree/path", _TreeGraphService_GetPathBetween0_HTTP_Handler(srv))
}

func _TreeGraphService_GetTreeNode0_HTTP_Handler(srv TreeGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in IdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTreeGraphServiceGetTreeNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTreeNode(ctx, req.(*IdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TreeNodeResp)
		return ctx.Result(200, reply)
	}
}

func _TreeGraphService_GetChildren0_HTTP_Handler(srv TreeGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PgIdReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTreeGraphServiceGetChildren)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChildren(ctx, req.(*PgIdReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TreeNodesResp)
		return ctx.Result(200, reply)
	}
}

func _TreeGraphService_GetTitleAutoComplete0_HTTP_Handler(srv TreeGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in TitleAutoCompleteReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTreeGraphServiceGetTitleAutoComplete)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetTitleAutoComplete(ctx, req.(*TitleAutoCompleteReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TitleAutoCompleteResp)
		return ctx.Result(200, reply)
	}
}

func _TreeGraphService_GetPathBetween0_HTTP_Handler(srv TreeGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPathReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationTreeGraphServiceGetPathBetween)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetPathBetween(ctx, req.(*GetPathReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*TreeNodeResp)
		return ctx.Result(200, reply)
	}
}

type TreeGraphServiceHTTPClient interface {
	GetChildren(ctx context.Context, req *PgIdReq, opts ...http.CallOption) (rsp *TreeNodesResp, err error)
	GetPathBetween(ctx context.Context, req *GetPathReq, opts ...http.CallOption) (rsp *TreeNodeResp, err error)
	GetTitleAutoComplete(ctx context.Context, req *TitleAutoCompleteReq, opts ...http.CallOption) (rsp *TitleAutoCompleteResp, err error)
	GetTreeNode(ctx context.Context, req *IdReq, opts ...http.CallOption) (rsp *TreeNodeResp, err error)
}

type TreeGraphServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewTreeGraphServiceHTTPClient(client *http.Client) TreeGraphServiceHTTPClient {
	return &TreeGraphServiceHTTPClientImpl{client}
}

func (c *TreeGraphServiceHTTPClientImpl) GetChildren(ctx context.Context, in *PgIdReq, opts ...http.CallOption) (*TreeNodesResp, error) {
	var out TreeNodesResp
	pattern := "/micros/graph/v1/tree/children"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTreeGraphServiceGetChildren))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TreeGraphServiceHTTPClientImpl) GetPathBetween(ctx context.Context, in *GetPathReq, opts ...http.CallOption) (*TreeNodeResp, error) {
	var out TreeNodeResp
	pattern := "/micros/graph/v1/tree/path"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTreeGraphServiceGetPathBetween))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TreeGraphServiceHTTPClientImpl) GetTitleAutoComplete(ctx context.Context, in *TitleAutoCompleteReq, opts ...http.CallOption) (*TitleAutoCompleteResp, error) {
	var out TitleAutoCompleteResp
	pattern := "/micros/graph/v1/tree/title-autocomplete"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTreeGraphServiceGetTitleAutoComplete))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *TreeGraphServiceHTTPClientImpl) GetTreeNode(ctx context.Context, in *IdReq, opts ...http.CallOption) (*TreeNodeResp, error) {
	var out TreeNodeResp
	pattern := "/micros/graph/v1/tree/node"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationTreeGraphServiceGetTreeNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
