// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v4.23.4
// source: api/rc/v3/rc.proto

package v3

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRcServiceInsertReportDecisionFactor = "/api.rc.v3.RcService/InsertReportDecisionFactor"
const OperationRcServiceListReport = "/api.rc.v3.RcService/ListReport"

type RcServiceHTTPServer interface {
	InsertReportDecisionFactor(context.Context, *InsertDependencyDataReq) (*SetDependencyDataResp, error)
	ListReport(context.Context, *ListReportKwdSearchReq) (*ListReportResp, error)
}

func RegisterRcServiceHTTPServer(s *http.Server, srv RcServiceHTTPServer) {
	r := s.Route("/")
	r.POST("/micros/rc/v3/report/decision-factor", _RcService_InsertReportDecisionFactor0_HTTP_Handler(srv))
	r.GET("/micros/rc/v3/report/list", _RcService_ListReport0_HTTP_Handler(srv))
}

func _RcService_InsertReportDecisionFactor0_HTTP_Handler(srv RcServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in InsertDependencyDataReq
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRcServiceInsertReportDecisionFactor)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.InsertReportDecisionFactor(ctx, req.(*InsertDependencyDataReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*SetDependencyDataResp)
		return ctx.Result(200, reply)
	}
}

func _RcService_ListReport0_HTTP_Handler(srv RcServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListReportKwdSearchReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRcServiceListReport)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListReport(ctx, req.(*ListReportKwdSearchReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListReportResp)
		return ctx.Result(200, reply)
	}
}

type RcServiceHTTPClient interface {
	InsertReportDecisionFactor(ctx context.Context, req *InsertDependencyDataReq, opts ...http.CallOption) (rsp *SetDependencyDataResp, err error)
	ListReport(ctx context.Context, req *ListReportKwdSearchReq, opts ...http.CallOption) (rsp *ListReportResp, err error)
}

type RcServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewRcServiceHTTPClient(client *http.Client) RcServiceHTTPClient {
	return &RcServiceHTTPClientImpl{client}
}

func (c *RcServiceHTTPClientImpl) InsertReportDecisionFactor(ctx context.Context, in *InsertDependencyDataReq, opts ...http.CallOption) (*SetDependencyDataResp, error) {
	var out SetDependencyDataResp
	pattern := "/micros/rc/v3/report/decision-factor"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRcServiceInsertReportDecisionFactor))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RcServiceHTTPClientImpl) ListReport(ctx context.Context, in *ListReportKwdSearchReq, opts ...http.CallOption) (*ListReportResp, error) {
	var out ListReportResp
	pattern := "/micros/rc/v3/report/list"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRcServiceListReport))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
