// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.3
// - protoc             v4.23.4
// source: api/graph/v1/graph_net.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationNetGraphServiceGetAvailableRelTypeToChildren = "/api.graph.v1.NetGraphService/GetAvailableRelTypeToChildren"
const OperationNetGraphServiceGetAvailableRelTypeToParents = "/api.graph.v1.NetGraphService/GetAvailableRelTypeToParents"
const OperationNetGraphServiceGetChildrenNet = "/api.graph.v1.NetGraphService/GetChildrenNet"
const OperationNetGraphServiceGetNetExpand = "/api.graph.v1.NetGraphService/GetNetExpand"
const OperationNetGraphServiceGetNode = "/api.graph.v1.NetGraphService/GetNode"
const OperationNetGraphServiceGetParentsNet = "/api.graph.v1.NetGraphService/GetParentsNet"

type NetGraphServiceHTTPServer interface {
	GetAvailableRelTypeToChildren(context.Context, *GetNodeReq) (*AvailableRelTypeResp, error)
	GetAvailableRelTypeToParents(context.Context, *GetNodeReq) (*AvailableRelTypeResp, error)
	GetChildrenNet(context.Context, *GetPaginationNodeReq) (*NetPaginationResp, error)
	GetNetExpand(context.Context, *NetExpandReq) (*NetResp, error)
	GetNode(context.Context, *GetNodeReq) (*NodeResp, error)
	GetParentsNet(context.Context, *GetPaginationNodeReq) (*NetPaginationResp, error)
}

func RegisterNetGraphServiceHTTPServer(s *http.Server, srv NetGraphServiceHTTPServer) {
	r := s.Route("/")
	r.GET("/micros/graph/v1/net/expand", _NetGraphService_GetNetExpand0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/net/node", _NetGraphService_GetNode0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/net/children", _NetGraphService_GetChildrenNet0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/net/parents", _NetGraphService_GetParentsNet0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/net/children/availableRelType", _NetGraphService_GetAvailableRelTypeToChildren0_HTTP_Handler(srv))
	r.GET("/micros/graph/v1/net/parents/availableRelType", _NetGraphService_GetAvailableRelTypeToParents0_HTTP_Handler(srv))
}

func _NetGraphService_GetNetExpand0_HTTP_Handler(srv NetGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in NetExpandReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNetGraphServiceGetNetExpand)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNetExpand(ctx, req.(*NetExpandReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NetResp)
		return ctx.Result(200, reply)
	}
}

func _NetGraphService_GetNode0_HTTP_Handler(srv NetGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNetGraphServiceGetNode)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetNode(ctx, req.(*GetNodeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NodeResp)
		return ctx.Result(200, reply)
	}
}

func _NetGraphService_GetChildrenNet0_HTTP_Handler(srv NetGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaginationNodeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNetGraphServiceGetChildrenNet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetChildrenNet(ctx, req.(*GetPaginationNodeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NetPaginationResp)
		return ctx.Result(200, reply)
	}
}

func _NetGraphService_GetParentsNet0_HTTP_Handler(srv NetGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetPaginationNodeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNetGraphServiceGetParentsNet)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetParentsNet(ctx, req.(*GetPaginationNodeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*NetPaginationResp)
		return ctx.Result(200, reply)
	}
}

func _NetGraphService_GetAvailableRelTypeToChildren0_HTTP_Handler(srv NetGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNetGraphServiceGetAvailableRelTypeToChildren)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAvailableRelTypeToChildren(ctx, req.(*GetNodeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AvailableRelTypeResp)
		return ctx.Result(200, reply)
	}
}

func _NetGraphService_GetAvailableRelTypeToParents0_HTTP_Handler(srv NetGraphServiceHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetNodeReq
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationNetGraphServiceGetAvailableRelTypeToParents)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetAvailableRelTypeToParents(ctx, req.(*GetNodeReq))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*AvailableRelTypeResp)
		return ctx.Result(200, reply)
	}
}

type NetGraphServiceHTTPClient interface {
	GetAvailableRelTypeToChildren(ctx context.Context, req *GetNodeReq, opts ...http.CallOption) (rsp *AvailableRelTypeResp, err error)
	GetAvailableRelTypeToParents(ctx context.Context, req *GetNodeReq, opts ...http.CallOption) (rsp *AvailableRelTypeResp, err error)
	GetChildrenNet(ctx context.Context, req *GetPaginationNodeReq, opts ...http.CallOption) (rsp *NetPaginationResp, err error)
	GetNetExpand(ctx context.Context, req *NetExpandReq, opts ...http.CallOption) (rsp *NetResp, err error)
	GetNode(ctx context.Context, req *GetNodeReq, opts ...http.CallOption) (rsp *NodeResp, err error)
	GetParentsNet(ctx context.Context, req *GetPaginationNodeReq, opts ...http.CallOption) (rsp *NetPaginationResp, err error)
}

type NetGraphServiceHTTPClientImpl struct {
	cc *http.Client
}

func NewNetGraphServiceHTTPClient(client *http.Client) NetGraphServiceHTTPClient {
	return &NetGraphServiceHTTPClientImpl{client}
}

func (c *NetGraphServiceHTTPClientImpl) GetAvailableRelTypeToChildren(ctx context.Context, in *GetNodeReq, opts ...http.CallOption) (*AvailableRelTypeResp, error) {
	var out AvailableRelTypeResp
	pattern := "/micros/graph/v1/net/children/availableRelType"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNetGraphServiceGetAvailableRelTypeToChildren))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NetGraphServiceHTTPClientImpl) GetAvailableRelTypeToParents(ctx context.Context, in *GetNodeReq, opts ...http.CallOption) (*AvailableRelTypeResp, error) {
	var out AvailableRelTypeResp
	pattern := "/micros/graph/v1/net/parents/availableRelType"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNetGraphServiceGetAvailableRelTypeToParents))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NetGraphServiceHTTPClientImpl) GetChildrenNet(ctx context.Context, in *GetPaginationNodeReq, opts ...http.CallOption) (*NetPaginationResp, error) {
	var out NetPaginationResp
	pattern := "/micros/graph/v1/net/children"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNetGraphServiceGetChildrenNet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NetGraphServiceHTTPClientImpl) GetNetExpand(ctx context.Context, in *NetExpandReq, opts ...http.CallOption) (*NetResp, error) {
	var out NetResp
	pattern := "/micros/graph/v1/net/expand"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNetGraphServiceGetNetExpand))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NetGraphServiceHTTPClientImpl) GetNode(ctx context.Context, in *GetNodeReq, opts ...http.CallOption) (*NodeResp, error) {
	var out NodeResp
	pattern := "/micros/graph/v1/net/node"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNetGraphServiceGetNode))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *NetGraphServiceHTTPClientImpl) GetParentsNet(ctx context.Context, in *GetPaginationNodeReq, opts ...http.CallOption) (*NetPaginationResp, error) {
	var out NetPaginationResp
	pattern := "/micros/graph/v1/net/parents"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationNetGraphServiceGetParentsNet))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
