// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"micros-dw/internal/biz"
	"micros-dw/internal/conf"
	"micros-dw/internal/data"
	"micros-dw/internal/server"
	"micros-dw/internal/service/dw/v2"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, cleanup, err := data.NewGormDb(confData)
	if err != nil {
		return nil, nil, err
	}
	mongoDb, cleanup2, err := data.NewMongoDb(confData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	dataData := data.NewData(db, mongoDb)
	dwEnterpriseRepo := data.NewDwEnterpriseRepo(dataData, logger)
	dwEnterpriseUsecase := biz.NewDwEnterpriseUsecase(dwEnterpriseRepo, logger)
	dwServiceServicer := v2.NewDwServiceServicer(dwEnterpriseUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, dwServiceServicer, logger)
	httpServer := server.NewHTTPServer(confServer, dwServiceServicer, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
