#server:
#  grpc:
#    addr: 0.0.0.0:50053
#    timeout: 10s
#
#data:
#  mongodb:
#    uri: mongodb://root:dev-password@192.168.44.169:27020
#  dwdata:
#    target: 192.168.44.150:50052

# Prod
server:
  grpc:
    addr: 0.0.0.0:50053
    timeout: 10s

data:
  mongodb:
    uri: mongodb://root:brillink8818mgo@10.0.232.121:27017
  dwdata:
    target: 10.0.232.22:50052
