server:
  http:
    addr: 0.0.0.0:8000
    timeout: 20s
  grpc:
    addr: 0.0.0.0:50051
    timeout: 20s

data:
  database:
    driver: mysql
#    source: "blscf:Dzkw46MZDbB7axDC@tcp(10.0.232.121:3308)/bl_business?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms"
    source: root:password-dev@tcp(192.168.44.169:3306)/data_spider?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
  redis:
    addr: 192.168.44.169:6379
    read_timeout: 1.0s
    write_timeout: 1.0s
    db: 3
    password: "aaa"
  nats:
    #    uri: "nats://dev:password@192.168.31.158:4222"
#    uri: nats://brillinkdata:MFmi9jAB@10.0.232.121:4222
    uri: nats://dev:password@192.168.44.169:4222
    activate: true
  blAuth:
    client_id: default
    client_secret: admin123
#    url: "http://10.0.232.22:9080"
    url: http://192.168.44.169:9080
    path_check_token: /admin-api/system/oauth2/check-token
    database:
      driver: mysql
      source: root:123@qwe@tcp(10.0.203.71:3306)/bl_basics?charset=utf8mb4&parseTime=True&loc=Local&timeout=10000ms
#  neo4j:
#      url: neo4j://10.0.232.121:7687
#      username: neo4j
#      password: bl@neo4j
  neo4j:
    url: neo4j://192.168.44.169:7687
    username: neo4j
    password: password
  minio:
    endpoint: 192.168.44.169:9030
    access_key: 58vRJBzl8o8FiZgdFAJS
    secret_key: Ge2fdEOu46tmpcE1yVFIzt1kHsYkFA0ue5h2P6Se
    use_ssl: false
  mongoDb:
    uri: mongodb://root:dev-password@192.168.44.169:27020
  service:
    dwdata_uri: 192.168.44.150:50052
#    pipeline_uri: 192.168.44.150:50053
    pipeline_uri: 192.168.44.150:50053
#    pipeline_uri: 192.168.31.114:50053
#    uri: mongodb://root:dev-password@localhost:27020
  consul:
    addr: 192.168.44.169:8500
#    addr: 100.82.108.1:8501
    token: d28b35c9-dcea-4ee7-d23c-33546400998f
  tls:
    folder_path: ../../../certs
